markdown: rdiscount
pygments: true

disqus_shortname: huangyu186
data_sources:
  - name: wedding # will be used as site.albums to access data, no spaces allowed
    type: json
    url:  http://i.91wedding.com/api/sites/huangyu/data?version=v1
